### PR TITLE
Notebook - Livestock detection using DeepForest

### LINKED ISSUE #6: [REVIEW] Livestock detection using DeepForest
# Notebook Review: Issue alan-turing-institute/notebooks-reviews#1 

<p align="left">
    <a href="http://mybinder.org/v2/gh/eds-book-gallery/95199651-9e81-4cae-a3a7-66398a9a5f62/review?labpath=notebook.ipynb">
        Binder
    </a>
</p>

**Submitting author:** @camappel

**Repository:** https://github.com/eds-book-gallery/95199651-9e81-4cae-a3a7-66398a9a5f62

**Notebook idea issue:** alan-turing-institute/eds-ideas-transfer#3 

**Editor:** @acocac 

**Reviewer:** @ethanwhite @louisavz

**Managing EiC:** @acocac 

## Status

**Reviewer instructions & questions**

Hi 👋 @ethanwhite @louisavz, please carry out your review in this issue by updating the checklist below. 

As a reviewer, you contribute to the technical quality of the content published by our community. 

Before the review, EiC checked if the submission fits the minimum requirements. 

The quality of the proposed contribution can be assessed through scientific, technical and code criteria. 

The reviewer guidelines are available here: https://edsbook.org/publishing/guidelines/guidelines-reviewers.html. 
Any questions/concerns please let @acocac know.

## Review checklist for @ethanwhite

*Please check off boxes as applicable, and elaborate in comments below. Your review is not limited to these topics, as described in the reviewer guide.*

### Conflict of interest
- [ ] As the reviewer I confirm that there are no conflicts of interest for me to review this work (If you are unsure whether you are in conflict, please speak to your editor _before_ starting your review).

### Code of conduct an peer-review principles
- [ ] I confirm that I read and will adhere to the Environmental Data Science [code of conduct](https://github.com/alan-turing-institute/environmental-ds-book/blob/master/CODE_OF_CONDUCT.md).
- [ ] I confirm that I read and will adhere to [Open Science Peer Review Oath](https://doi.org/10.12688/f1000research.5686.2) 

### General checks
- [ ] **Notebook:** Is the notebook file (``notebook.ipynb``) part of the notebook repository?
- [ ] **Contribution and authorship:** Does the author list seem appropriate and complete (full name, affiliation, and GitHub/ORCID handle)?
- [ ] **Scope and eligibility:** Does the submission contain an original and complete analysis according to the [scope of EDS book](https://edsbook.org/notebooks/about/aims-and-scope.html#aims-and-scope)?

### Reproducibility
- [ ] Does the notebook run in a local environment?
- [ ] Does the notebook build and run in binder?
- [ ] Are all data sources openly accessible and properly cited (e.g. with citation to a persistent DOI) in the heading section?

### Pedagogy
- [ ] Are the notebook purpose and highlights clear?
- [ ] Does the notebook demonstrate some specific data analysis or visualisation techniques?
- [ ] Is the notebook well documented, using both markdown cells and comments in code cells?
- [ ] Does the conclusion section provide clear and concise final say on the tools, analysis and/or datasets used?
- [ ] Is the notebook narrative well written (it does not require editing for structure, language, or writing quality)?

### Ethical
- [ ] Is any linkage of datasets in the notebook unlikely to lead to an increased risk of the personal identification of individuals?
- [ ] Is the notebook truthful and clear about any limitations of the analysis (and potential biases in data and/or tools)?
- [ ] Is the notebook unlikely to lead to negative social outcomes, such as (but not limited to) increasing discrimination or injustice?

### Other Requirements
- [ ] All mentioned software should be formally and consistently cited wherever possible.
- [ ] Acronyms should be spelled out upon first mention.
- [ ] License conditions on images and figures must be respected (Creative Commons, etc.).

### Final approval (post-review)

- [ ] **Authors has responded to my review and made changes to my satisfaction. I recommend approving the notebook for publication.**

## Review checklist for @louisavz

*Please check off boxes as applicable, and elaborate in comments below. Your review is not limited to these topics, as described in the reviewer guide.*

### Conflict of interest
- [ ] As the reviewer I confirm that there are no conflicts of interest for me to review this work (If you are unsure whether you are in conflict, please speak to your editor _before_ starting your review).

### Code of conduct an peer-review principles
- [ ] I confirm that I read and will adhere to the Environmental Data Science [code of conduct](https://github.com/alan-turing-institute/environmental-ds-book/blob/master/CODE_OF_CONDUCT.md).
- [ ] I confirm that I read and will adhere to [Open Science Peer Review Oath](https://doi.org/10.12688/f1000research.5686.2) 

### General checks
- [ ] **Notebook:** Is the notebook file (``notebook.ipynb``) part of the notebook repository?
- [ ] **Contribution and authorship:** Does the author list seem appropriate and complete (full name, affiliation, and GitHub/ORCID handle)?
- [ ] **Scope and eligibility:** Does the submission contain an original and complete analysis according to the [scope of EDS book](https://edsbook.org/notebooks/about/aims-and-scope.html#aims-and-scope)?

### Reproducibility
- [ ] Does the notebook run in a local environment?
- [ ] Does the notebook build and run in binder?
- [ ] Are all data sources openly accessible and properly cited (e.g. with citation to a persistent DOI) in the heading section?

### Pedagogy
- [ ] Are the notebook purpose and highlights clear?
- [ ] Does the notebook demonstrate some specific data analysis or visualisation techniques?
- [ ] Is the notebook well documented, using both markdown cells and comments in code cells?
- [ ] Does the conclusion section provide clear and concise final say on the tools, analysis and/or datasets used?
- [ ] Is the notebook narrative well written (it does not require editing for structure, language, or writing quality)?

### Ethical
- [ ] Is any linkage of datasets in the notebook unlikely to lead to an increased risk of the personal identification of individuals?
- [ ] Is the notebook truthful and clear about any limitations of the analysis (and potential biases in data and/or tools)?
- [ ] Is the notebook unlikely to lead to negative social outcomes, such as (but not limited to) increasing discrimination or injustice?

### Other Requirements
- [ ] All mentioned software should be formally and consistently cited wherever possible.
- [ ] Acronyms should be spelled out upon first mention.
- [ ] License conditions on images and figures must be respected (Creative Commons, etc.).

### Final approval (post-review)

- [ ] **Authors has responded to my review and made changes to my satisfaction. I recommend approving the notebook for publication.**

## Additional instructions

Reviewer general comments are welcome on this REVIEW issue or directly to the notebook repository.

If you do the latter, you will find a Pull Request titled [REVIEW](https://github.com/eds-book-gallery/95199651-9e81-4cae-a3a7-66398a9a5f62/pull/5) where you can carry out the discussion with authors through ReviewNB, a third-party plugin in GitHub for displaying and commenting Jupyter Notebooks (see further details [here](https://edsbook.org/notebooks/about/notebooks-technologies.html#reviewnb)). 

In addition to ReviewNB, we suggest to explore or run the notebook in:
* **Binder** (run): Click the Launch Binder button at the top level of this message.

### LINKED ISSUE #260: [REVIEW] Livestock detection using DeepForest
# Notebook Review: Issue #259 

<p align="left">
    <a href="http://mybinder.org/v2/gh/eds-book-gallery/95199651-9e81-4cae-a3a7-66398a9a5f62/review?labpath=notebook.ipynb">
        Binder
    </a>
</p>

**Submitting author:** @camappel

**Repository:** https://github.com/eds-book-gallery/95199651-9e81-4cae-a3a7-66398a9a5f62

**Notebook idea issue:** #257 

**Editor:** @acocac 

**Reviewer:** @ethanwhite @louisavz

**Managing EiC:** @acocac 

## Status

**Reviewer instructions & questions**

Hi 👋 @ethanwhite @louisavz, please carry out your review in this issue by updating the checklist below. 

As a reviewer, you contribute to the technical quality of the content published by our community. 

Before the review, EiC checked if the submission fits the minimum requirements. 

The quality of the proposed contribution can be assessed through scientific, technical and code criteria. 

The reviewer guidelines are available here: https://edsbook.org/publishing/guidelines/guidelines-reviewers.html. 
Any questions/concerns please let @acocac know.

## Review checklist for @ethanwhite

*Please check off boxes as applicable, and elaborate in comments below. Your review is not limited to these topics, as described in the reviewer guide.*

### Conflict of interest
- [ ] As the reviewer I confirm that there are no conflicts of interest for me to review this work (If you are unsure whether you are in conflict, please speak to your editor _before_ starting your review).

### Code of conduct an peer-review principles
- [ ] I confirm that I read and will adhere to the Environmental Data Science [code of conduct](https://github.com/alan-turing-institute/environmental-ds-book/blob/master/CODE_OF_CONDUCT.md).
- [ ] I confirm that I read and will adhere to [Open Science Peer Review Oath](https://doi.org/10.12688/f1000research.5686.2) 

### General checks
- [ ] **Notebook:** Is the notebook file (``notebook.ipynb``) part of the notebook repository?
- [ ] **Contribution and authorship:** Does the author list seem appropriate and complete (full name, affiliation, and GitHub/ORCID handle)?
- [ ] **Scope and eligibility:** Does the submission contain an original and complete analysis according to the [scope of EDS book](https://edsbook.org/notebooks/about/aims-and-scope.html#aims-and-scope)?

### Reproducibility
- [ ] Does the notebook run in a local environment?
- [ ] Does the notebook build and run in binder?
- [ ] Are all data sources openly accessible and properly cited (e.g. with citation to a persistent DOI) in the heading section?

### Pedagogy
- [ ] Are the notebook purpose and highlights clear?
- [ ] Does the notebook demonstrate some specific data analysis or visualisation techniques?
- [ ] Is the notebook well documented, using both markdown cells and comments in code cells?
- [ ] Does the conclusion section provide clear and concise final say on the tools, analysis and/or datasets used?
- [ ] Is the notebook narrative well written (it does not require editing for structure, language, or writing quality)?

### Ethical
- [ ] Is any linkage of datasets in the notebook unlikely to lead to an increased risk of the personal identification of individuals?
- [ ] Is the notebook truthful and clear about any limitations of the analysis (and potential biases in data and/or tools)?
- [ ] Is the notebook unlikely to lead to negative social outcomes, such as (but not limited to) increasing discrimination or injustice?

### Other Requirements
- [ ] All mentioned software should be formally and consistently cited wherever possible.
- [ ] Acronyms should be spelled out upon first mention.
- [ ] License conditions on images and figures must be respected (Creative Commons, etc.).

### Final approval (post-review)

- [ ] **Authors has responded to my review and made changes to my satisfaction. I recommend approving the notebook for publication.**

## Review checklist for @louisavz

*Please check off boxes as applicable, and elaborate in comments below. Your review is not limited to these topics, as described in the reviewer guide.*

### Conflict of interest
- [ ] As the reviewer I confirm that there are no conflicts of interest for me to review this work (If you are unsure whether you are in conflict, please speak to your editor _before_ starting your review).

### Code of conduct an peer-review principles
- [ ] I confirm that I read and will adhere to the Environmental Data Science [code of conduct](https://github.com/alan-turing-institute/environmental-ds-book/blob/master/CODE_OF_CONDUCT.md).
- [ ] I confirm that I read and will adhere to [Open Science Peer Review Oath](https://doi.org/10.12688/f1000research.5686.2) 

### General checks
- [ ] **Notebook:** Is the notebook file (``notebook.ipynb``) part of the notebook repository?
- [ ] **Contribution and authorship:** Does the author list seem appropriate and complete (full name, affiliation, and GitHub/ORCID handle)?
- [ ] **Scope and eligibility:** Does the submission contain an original and complete analysis according to the [scope of EDS book](https://edsbook.org/notebooks/about/aims-and-scope.html#aims-and-scope)?

### Reproducibility
- [ ] Does the notebook run in a local environment?
- [ ] Does the notebook build and run in binder?
- [ ] Are all data sources openly accessible and properly cited (e.g. with citation to a persistent DOI) in the heading section?

### Pedagogy
- [ ] Are the notebook purpose and highlights clear?
- [ ] Does the notebook demonstrate some specific data analysis or visualisation techniques?
- [ ] Is the notebook well documented, using both markdown cells and comments in code cells?
- [ ] Does the conclusion section provide clear and concise final say on the tools, analysis and/or datasets used?
- [ ] Is the notebook narrative well written (it does not require editing for structure, language, or writing quality)?

### Ethical
- [ ] Is any linkage of datasets in the notebook unlikely to lead to an increased risk of the personal identification of individuals?
- [ ] Is the notebook truthful and clear about any limitations of the analysis (and potential biases in data and/or tools)?
- [ ] Is the notebook unlikely to lead to negative social outcomes, such as (but not limited to) increasing discrimination or injustice?

### Other Requirements
- [ ] All mentioned software should be formally and consistently cited wherever possible.
- [ ] Acronyms should be spelled out upon first mention.
- [ ] License conditions on images and figures must be respected (Creative Commons, etc.).

### Final approval (post-review)

- [ ] **Authors has responded to my review and made changes to my satisfaction. I recommend approving the notebook for publication.**

## Additional instructions

Reviewer general comments are welcome on this REVIEW issue or directly to the notebook repository.

If you do the latter, you will find a Pull Request titled [REVIEW](https://github.com/eds-book-gallery/95199651-9e81-4cae-a3a7-66398a9a5f62/pull/5) where you can carry out the discussion with authors through ReviewNB, a third-party plugin in GitHub for displaying and commenting Jupyter Notebooks (see further details [here](https://edsbook.org/notebooks/about/notebooks-technologies.html#reviewnb)). 

In addition to ReviewNB, we suggest to explore or run the notebook in:
* **Binder** (run): Click the Launch Binder button at the top level of this message.

### PR DESCRIPTION
**Pull request by acocac**
### Summary

Postprint version from the notebook submission (Fixes alan-turing-institute/notebooks-reviews#6).

#### Editors-in-chief 

Before review:
* [x] Add submodule from the notebook repo
* [x] Add new submodule path to `_toc.yml`
* [x] Add card of the new notebook
* [x] Add references
* [x] Hide code cell content of some sections e.g. Libraries, Tables, Last tested
* [x] Right-panel looks ok (headings)

Once reviewed/approved:
* [x] Add reviewers and editor
* [x] Generate conda-lock
* [x] Generate RoHub
* [x] Replace binder url, postprint to main
* [x] Replace submodule branch, preview to render
* [x] Generate and add badges of DOI in the notebook file and gallery
* [x] Check badges in the gallery and notebook file
* [x] Check binder
* [ ] Add authors/reviewers via all-contributors
 
### What should author(s) concentrate their feedback on?

- [ ] Check the rendered version in the [Netlify Preview]() looks ok.
- [ ] Check the [card/thumbnail of the notebook]() is correctly displayed in the Gallery. Are the suggested short notebook title in the gallery and left menu ok?

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/main/README.md#contributors) in the README file.
- [x] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/main/README.md#contributors) in the README file: 

**Authors**
  - [x] camappel

**Reviewers**
  - [x] ethanwhite
  - [x] louisavz

### CODE REVIEW

**Comment by acocac** [comment]
Hi @camappel

This PR aims to provide a preview of the post-print version of your notebook submission. We appreciate  completing the post-review check-list for authors in the PR description. Additional comments would be welcome!

> ### What should author(s) concentrate their feedback on?
> * [ ]  Check the rendered version in the [Netlify Preview](https://deploy-preview-262--the-environmental-ds-book.netlify.app/notebooks/gallery/95199651-9e81-4cae-a3a7-66398a9a5f62/notebook) looks ok.
> * [ ]  Check the [card/thumbnail of the notebook](https://deploy-preview-262--the-environmental-ds-book.netlify.app/notebooks/gallery) is correctly displayed in the Gallery. Are the suggested short notebook title in the gallery and left menu ok?

**Comment by camappel** [comment]
Very happy with the thumbnail/titles/content. The commented out chunks look much better than in Jupyter!

Thanks a lot for the finishing touches e.g. adding to the modelling publications and pushing this over the line!

Only comment is the DOI in the badge in gallery appears to be the same as the one for sea ice forecasting - but I'm guessing this is just a placeholder?

- [x] Check the rendered version in the [Netlify Preview](https://deploy-preview-262--the-environmental-ds-book.netlify.app/notebooks/gallery/95199651-9e81-4cae-a3a7-66398a9a5f62/notebook) looks ok.
- [x] Check the [card/thumbnail of the notebook](https://deploy-preview-262--the-environmental-ds-book.netlify.app/notebooks/gallery) is correctly displayed in the Gallery. Are the suggested short notebook title in the gallery and left menu ok?
(I can't edit the checklist directly as I'm not a reviewer to the PR)

**Comment by acocac** [comment]
> Very happy with the thumbnail/titles/content. The commented out chunks look much better than in Jupyter!

> Thanks a lot for the finishing touches e.g. adding to the modelling publications and pushing this over the line!

Thanks for confirming the notebook and content in general looks ok. The publication of the notebook won't be possible without your constant effort to learn, connect and practice your skills for the benefit of the international open environmental data science community!

> Only comment is the DOI in the badge in gallery appears to be the same as the one for sea ice forecasting - but I'm guessing this is just a placeholder?

Yes, this is a placeholder which will be addressed when we generate the DOI of the notebook.

> * [x]  Check the rendered version in the [Netlify Preview](https://deploy-preview-262--the-environmental-ds-book.netlify.app/notebooks/gallery/95199651-9e81-4cae-a3a7-66398a9a5f62/notebook) looks ok.
> * [x]  Check the [card/thumbnail of the notebook](https://deploy-preview-262--the-environmental-ds-book.netlify.app/notebooks/gallery) is correctly displayed in the Gallery. Are the suggested short notebook title in the gallery and left menu ok?
>   (I can't edit the checklist directly as I'm not a reviewer to the PR)

We will work on the final preparation of the notebook. We'll share in this thread examples of the Ads to be posted among the communication channels of EDS book. 

Re the official publication date, we suggest **Monday 9th December, 13:00 (GMT)**. Mondays is the preferred date when we announce new notebooks. Please let me know if it works for you!

**Comment by camappel** [comment]
No problem with the thread being shared. Monday 9th December, 13:00 (GMT) works great for me - I'm looking forward to the publication

**Comment by acocac** [comment]
@all-contributors please add @camappel for blog, code

**Comment by acocac** [comment]
@all-contributors please add @ethanwhite

**Comment by acocac** [comment]
@all-contributors please add @ethanwhite for review

**Comment by acocac** [comment]
@all-contributors please add @louisavz for review

**Comment by acocac** [comment]
@camappel fyi- I've merged the PR into the main branch. This means the notebook is now live in EDS book, however the official launch is Monday next week. 

I'll share later drafts of the Ads to be posted in social media (please let me know if you have an account in Mastodon or Bluesky). You're welcome to become member of EDS book group in [LinkedIn](https://www.linkedin.com/groups/13116833/) too.

**Comment by camappel** [comment]
Great, thanks very much for adding me as a contributor. I've joined the LinkedIn but I'm not on other socials. Looking forward to the launch! I'll share it in my channel as well

**Pull request merged**
