### PR TITLE
[WIP] Notebook - general-preprocessing-rainfall_noaa

### LINKED ISSUE #9: [NBI] Concatenating a gridded rainfall dataset into a time series
## What is the notebook about?

Calculate dry season rainfall averages in Borneo based on a gridded dataset and create a time series 

## Data Science Component

- [ ] Sensor visualisation
- [x] Preprocessing
- [ ] Modelling
- [ ] Post-processing
- [ ] Other: 

## Checklist:

- [x] Input data, pipeline and/or model are public with license/citation
- [x] The proposed notebook reuses existing codebase
- [x] The proposed notebook uses open-source packages
- [x] The proposed notebook is associated to existing publication(s)

## Additional information 

Source of data: https://psl.noaa.gov/data/gridded/data.ncep.reanalysis.html
Publication: https://journals.ametsoc.org/view/journals/bams/102/12/BAMS-D-20-0117.1.xml

Steps are as follows:
1. Load gridded rainfall dataset
2. Create seasonal means
3. Extract the study region
4. Create area-averaged time series
5. Extract the dry season and restrict to the study timeframe
6. Plot the time series

### PR DESCRIPTION
**Pull request by acocac**
## Before review
- [ ] Work in progress
- [x] Ready for review
- [ ] Need help!

## Description

Add notebook in preprocessing NOAA timeseries for rainfall analysis at global scale and Borneo (see notebook idea in https://github.com/alan-turing-institute/eds-ideas-transfer/issues/9).

## Motivation and Context

New notebook for the preprocessing theme.

## How has this been tested?

GitHub actions deployed first in the forked templated by the main author, @timo0thy, then forked repo was transferred to the EnvDS book organisation (see https://github.com/Environmental-DS-Book/general-preprocessing-rainfall_noaa).

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] New notebook and/or content
- [ ] Documentation notebook/content update 
- [ ] Other (please describe):
- [ ] Feature change (upgrade version)

## Checklist:

- [x] My code follows the code style of this project: [Python](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [CONTRIBUTING](../CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests to cover my changes
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage)

### CODE REVIEW

**Comment by acocac** [comment]
@NHomer-Edi @timo0thy can you double check if the version in the Netlify preview is the latest one of the round 1? Just add thumbs-up if the preview is ok. Then, I'll add some suggestions for a 2nd round in the notebook repository.

**Comment by timo0thy** [comment]
Looks all good to me, thanks!

**Comment by NHomer-Edi** [comment]
👍

**Comment by acocac** [comment]
@timo0thy @NHomer-Edi I've finished the post-print stage (i.e. styling, adding badges, minor changes) of the notebook. May I ask to double check the Netlify preview and inspect if the Binder and links of the the notebook work for you. Note, the Rohub is incomplete, but I hope to have it ready before the release of the notebook Monday next week.

**Comment by NHomer-Edi** [comment]
@acocac The Netflify preview and Binder work well for me - no issues to report.

**Review by timo0thy — APPROVED** [review]
Sorry for taking a day to get back to you, but it works perfect on both Netlify and Binder. Thanks!

**Pull request merged**
