### PR TITLE
SEVIRI Wildfire Notebook

### PR DESCRIPTION
**Pull request by samueljackson92**
Long overdue: a PR for contributing a SEVIRI data demonstrator notebook to the Environmental AI book. This notebook:

* Use `satpy` to load, visualise, and regrid SEVIRI level 1.5 data.
* Fetch a fire database containing some 880 fires from September 1s5, 2020.
* Visualisation of fire pixels from the database
* Visualisation of the fire pixels alongside bands from the SEVIRI satellite data.

@acocac let me know if there is anything I need to adjust or add.

### CODE REVIEW

**Comment by acocac** [comment]
@samueljackson92 Thanks for the contribution, very nice work! I added some suggestions to make the notebook compatible with the latest version of the EnvAI book.  Find below some general comments:

- We need to work on the best strategy to keep the fire pixel data in safer and more stable storage e.g. Zenodo instead of your personal Google Drive. 
- It would be great to highlight the custom intake driver. Indeed, please mention you successfully integrate `satpy` and `intake` to fetch MODIS data by cross-referencing the MODIS notebook.
- I've found great you mention the tip of `rasterize=False`!

**Comment by samueljackson92** [comment]
Hi @acocac. Thanks for the comments. I think I agree with all your comments. I'll find some time to make the suggested changes. I agree Zenodo is probably the best option for stability. I also think it might be worth spinning out the intake driver to a separate repo/library.

**Comment by acocac** [comment]
Hi @samueljackson92, thanks for the reply, no rush. I'll find a way to keep a Zenodo repo linked to a research group, in this case the Environmental AI book. I'll keep you informed about my progress here.

**Comment by samueljackson92** [comment]
@acocac Updated!

The only thing I have not changed is the requirement for Google Drive. For now, I wait for the Zenodo solution or similar.

**Comment by acocac** [comment]
<p><a href="https://github.com/samueljackson92" target="_blank">@samueljackson92</a>, the notebook is ready to go so we can release it after a test in Binder tomorrow morning.</p><p> </p><p>FYI, I pushed some changes to fully integrate the notebook with the new template describing further metadata, fix some minor typos and replace fetching the fire sample data from <em>gdrive</em> by a <em>zenodo</em> repository hosted by <a href="https://zenodo.org/communities/the-environmental-ds-community/?page=1&amp;size=20" target="_blank">the Environmental Data Science community</a>. I've found this route could lead us to follow <a href="https://about.zenodo.org/principles/" target="_blank">FAIR principles</a> to share/curate future sample data for the Environmental AI book.</p><p> </p><p>Finally, as part of the transparency and credits, it would be great if we can add some key metadata to the <a href="https://zenodo.org/record/5717106#.YZrEEfHP30o" target="_blank">Zenodo repository</a> i.e. further details of the original source and preprocessing steps would be very helpful e.g. how did you subset the dates? In addition, can you also share your ORCID?</p>

**Review by acocac — APPROVED** [review]

**Pull request merged**
