### PR TITLE
Add soil moisture notebook 

### LINKED ISSUE #11: [NBI] COSMOS-UK Sensor Visualisation
## What is the notebook about?

- COSMOS-UK, https://catalogue.ceh.ac.uk/documents/b5c190e4-e35d-40ea-8fbe-598da03a1185
- intake, hvplot, xarray

## Data Science Component

- [x] Sensor visualisation
- [ ] Preprocessing
- [ ] Modelling
- [ ] Post-processing
- [ ] Other: 

## Checklist:

- [x] Input data, pipeline and/or model are public with license/citation
- [ ] The proposed notebook reuses existing codebase
- [x] The proposed notebook uses open-source packages
- [x] The proposed notebook is associated to existing publication(s)

### PR DESCRIPTION
**Pull request by acocac**
## Before review
- [ ] Work in progress
- [x] Ready for review
- [ ] Need help!

## Description

This notebook refers to explore COSMOS-UK dataset

## Motivation and Context

There are not use case in agriculture with soil moisture.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] New notebook and/or content
- [ ] Documentation notebook/content update 
- [ ] Other (please describe):
- [ ] Feature change (upgrade version)

## Checklist:

- [x] My code follows the code style of this project: [Python](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [CONTRIBUTING](../CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests to cover my changes
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage)

### CODE REVIEW

**Comment by dorankhamis** [comment]
<p>Some comments on the text:</p><ul><li>"delivers field-scale soil water volumetric content (VWC) [<em>something</em>] for around 50 sites" where something could be observations or measurements?</li><li>The PE value is not actually measured "daily total evapotranspiration" but theoretical <em>potential evapotranspiration</em> calculated from the meteorological measurements at the site. PE is an <em>ideal</em> maximum evapotranspiration that could occur over well-watered grassland given the weather conditions that day (though don't quote me exactly on that, best to look up a definition).</li><li>&nbsp;"estimated variable measurement depth ofbetween" typo. It probably worth mentioning in this paragraph that the measurement depth depends on moisture content of the soil: the wetter it is, the more shallow the measurement 'bowl'.</li><li>Again, the sentence about PE under the Timeseries heading: "PE refers to the potential evaporation from soils plus transpiration by plants and is strongly influenced by the available soil moisture" actually PE does not depend on soil moisture at all, it <em>assumes </em>there is always adequate moisture to match the <em>demand </em>for evapotranspiration from the meteorology and vegetation.</li><li>"These sensors measure point-based soil moisture at different depths" about the TDT sensors; I'm struggling with the phrase "point-based" (and in fact "point-scale" which occurs at the very start of the notebook). I prefer to think about the TDT sensor providing point measurements or measurements at a point, or when comparing TDT to CRNS: local vs site measurements. Perhaps just personal preference.</li><li>"This procedure requires to resample TDT measurements": <em>It is necessary to resample the TDT measurements</em></li></ul><p> </p><p>Other comments:</p><ul><li>I like the intake code, probably doing a bite-sized version of what the COSMOS-UK API will do! Though I'm imagining trying to write similar intake code for the flux tower data which isn't standardised like the COSMOS data so every site is in a different format...!</li><li>The correlation section where you correlate PE with VWC is interesting but the text is perhaps slightly misleading (this following on from the point about PE not depending on soil moisture). There is no "close relationship" between PE and VWC other than that the meteorological conditions affected PE also affect soil moisture -- so they are linked in a second-order way, if you like. While the VWC is a direct observation of the moisture, the PE is a theoretical estimate of a hypothetical maximum removal of moisture NOT the actual removal of moisture. But saying that, there is of course a seasonal relationship between those variables due to the shifting meteorology over the seasons and the changing <em>potential </em>or <em>demand </em>for evapotranspiration that arises from that.</li><li>The heatmap is a nice clean way to visualise the relatively noisy soil moisture timeseries, although for some reason I want to flip the colours round so that red means high and blue means low. I know this is against the "red = hot and dry, blue = wet" intuition so maybe ignore me!</li><li>It might be worth adding a sentence or two about why the TDT probes don't match the CRNS VWC, or even each other, exactly. The complexity of the porous structure of soil even under "simple" grassland means that moisture can be non-uniformly distributed horizontally and vertically: two probes a few metres apart measure "extremely local" moisture (and can sometimes be trapped in a water pocket leading to artificially high VWC or be pressed against a rock and produce artificially low VWC). The COSMOS CRNS averages over all of this heterogeneity but introduces its own sources of noise (biomass water, surface water, variable depth and horizontal footprint).</li></ul><p> </p><p>Overall, very nice overview!</p><p> </p>

**Comment by mattfry-ceh** [comment]
<p>Comments from me:</p><p> </p><p>In general this is great, a nice way to show the data and the tools. I like the use of the csv metadata files to use for graph labelling, etc. (which is what we meant them to be used for).</p><p> </p><p>Some specific small points:</p><ul><li>could the link at top ("the&nbsp;<a href="https://catalogue.ceh.ac.uk/documents/b5c190e4-e35d-40ea-8fbe-598da03a1185" target="_blank">2013-2019 public COSMOS-UK dataset</a>") point to the DOI as this is immutable:  <a href="https://doi.org/10.5285/b5c190e4-e35d-40ea-8fbe-598da03a1185" target="_blank">https://doi.org/10.5285/b5c190e4-e35d-40ea-8fbe-598da03a1185</a></li><li>The sentence "Additional to inform near-surface soil moisture, the network collects a large number of hydrometeorological and soil data variables, including VWC measured by point-scale soil moisture sensors" doesn't quite capture it. The COSMOS sensors aren't near-surface, compared to most soil moisture sensors. One key points is that, in contrast to point sensors they measure SM over a wider footprint. How about "In addition to measuring field-scale soil moisture, the network collects a large number of hydrometeorological and soil data variables, including VWC measured by point-scale soil moisture sensors."</li><li>Could the dataset authors text use the full citation for the dataset: "Stanley, S.; Antoniou, V.; Askquith-Ellis, A.; Ball, L.A.; Bennett, E.S.; Blake, J.R.; Boorman, D.B.; Brooks, M.; Clarke, M.; Cooper, H.M.; Cowan, N.; Cumming, A.; Evans, J.G.; Farrand, P.; Fry, M.; Hitt, O.E.; Lord, W.D.; Morrison, R.; Nash, G.V.; Rylett, D.; Scarlett, P.M.; Swain, O.D.; Szczykulska, M.; Thornton, J.L.; Trill, E.J.; Warwick, A.C.; Winterbourn, B. (2021). Daily and sub-daily hydrometeorological and soil data (2013-2019) [COSMOS-UK]. NERC Environmental Information Data Centre.&nbsp;<a href="https://doi.org/10.5285/b5c190e4-e35d-40ea-8fbe-598da03a1185" target="_blank">https://doi.org/10.5285/b5c190e4-e35d-40ea-8fbe-598da03a1185</a>"</li><li>Could dataset authors section be called "Dataset reference and documentation", because the supporting documentation at this link is probably the most accessible to most users</li><li>Could the "Dataset documentation" section be called "Further references" as these are more about proving background to the COSMOS network and methods.</li><li>Under the "Note" section, which is great, thanks, can we put the link again, just to be sure! Maybe the text "available for download" could have the DOI link above.</li><li>Additional Information: again, change the dataset link to use the DOI.</li></ul><p> </p><p> </p>

**Comment by acocac** [comment]
<p>@<a href="https://github.com/dorankhamis" target="_blank">dorankhamis</a>, thanks for the feedback. It really helps to improve the notebook content and fix some misleading text. Please find below my comments below:</p><p> </p><p>Some comments on the text:</p><ul><li>"delivers field-scale soil water volumetric content (VWC) [<em>something</em>] for around 50 sites" where something could be observations or measurements?</li></ul><ol><li>Added <em>measurements</em></li></ol><p> </p><ul><li>The PE value is not actually measured "daily total evapotranspiration" but theoretical&nbsp;<em>potential evapotranspiration</em>&nbsp;calculated from the meteorological measurements at the site. PE is an&nbsp;<em>ideal</em>&nbsp;maximum evapotranspiration that could occur over well-watered grassland given the weather conditions that day (though don't quote me exactly on that, best to look up a definition).</li></ul><ol><li>Rephrased in the highlights, Explore relationships between daily mean soil moisture and <em>potential evapotranspiration derived from the meteorological measurements at the site</em>.</li></ol><p> </p><ul><li>&nbsp;"estimated variable measurement depth ofbetween" typo. It probably worth mentioning in this paragraph that the measurement depth depends on moisture content of the soil: the wetter it is, the more shallow the measurement 'bowl'.</li></ul><ol><li>Fixed the typo and added a sentence indicating the relationship between measurement depth and soil wetness:</li><li><em>It is worth mentioning the measurement depth depends on the soil moisture content as&nbsp;well&nbsp;as&nbsp;lattice&nbsp;water&nbsp;and&nbsp;soil&nbsp;organic&nbsp;matter&nbsp;water&nbsp;equivalent (see Cooper et al. 2021). The&nbsp;greater&nbsp;the&nbsp;actual soil water content, the shallower the penetrative depth.</em></li></ol><p> </p><ul><li>Again, the sentence about PE under the Timeseries heading: "PE refers to the potential evaporation from soils plus transpiration by plants and is strongly influenced by the available soil moisture" actually PE does not depend on soil moisture at all, it&nbsp;<em>assumes&nbsp;</em>there is always adequate moisture to match the&nbsp;<em>demand&nbsp;</em>for evapotranspiration from the meteorology and vegetation.</li></ul><ol><li>Rephrased as follows, PE refers to the potential evaporation from soils plus transpiration by plants <em>(so called evapotranspiration). PE assumes there is always adequate moisture to match the evapotranspiration demand.</em></li></ol><p> </p><ul><li>"These sensors measure point-based soil moisture at different depths" about the TDT sensors; I'm struggling with the phrase "point-based" (and in fact "point-scale" which occurs at the very start of the notebook). I prefer to think about the TDT sensor providing point measurements or measurements at a point, or when comparing TDT to CRNS: local vs site measurements. Perhaps just personal preference.</li></ul><ol><li>Field- and point-scale are valid terms but just in case I'm adding local and site next to each term in the sensor description.</li><li>In addition to measuring field-scale <em>i.e. local</em> soil moisture, the network collects a large number of hydrometeorological and soil data variables, including VWC measured by point-scale<em> i.e. site</em> soil moisture sensors.</li><li>For the remaining text, I'm changing point-scale and point-based as follows:</li><li>point-scale to site in <em>Compare local and site soil moisture measurements at daily resolution.</em></li><li>These sensors provide <em>point measurements</em> of soil moisture at different depths as it commonly conducted in soil moisture in-situ sensing</li></ol><p> </p><ul><li>"This procedure requires to resample TDT measurements":&nbsp;<em>It is necessary to resample the TDT measurements</em></li></ul><ol><li>Rephrased, <em>To compare CNRSs (local) and TDT (site) soil moisture measurements at daily resolution, it is necessary to resample the TDT measurements from subhourly to daily.</em></li></ol><p> </p><p>Other comments:</p><ul><li>I like the intake code, probably doing a bite-sized version of what the COSMOS-UK API will do! Though I'm imagining trying to write similar intake code for the flux tower data which isn't standardised like the COSMOS data so every site is in a different format...!</li></ul><ol><li>Glad to hear you've found the intake YML catalog useful! I configured it using the same folder structure of the full dataset in case potential users are curious to explore it with the notebook. I understand the challenges with the flux tower sites, however, if you're using the public dataset, I would suggest follow a demonstrator of the FluxNet dataset in PyViz, https://examples.pyviz.org/carbon_flux/carbon_flux.html</li></ol><p> </p><ul><li>The correlation section where you correlate PE with VWC is interesting but the text is perhaps slightly misleading (this following on from the point about PE not depending on soil moisture). There is no "close relationship" between PE and VWC other than that the meteorological conditions affected PE also affect soil moisture -- so they are linked in a second-order way, if you like. While the VWC is a direct observation of the moisture, the PE is a theoretical estimate of a hypothetical maximum removal of moisture NOT the actual removal of moisture. But saying that, there is of course a seasonal relationship between those variables due to the shifting meteorology over the seasons and the changing&nbsp;<em>potential&nbsp;</em>or&nbsp;<em>demand&nbsp;</em>for evapotranspiration that arises from that.</li></ul><ol><li>You've made a fair point here. I modified the sentence by removing the close relationship to avoid misleading the reader.</li><li><em>To explore further the seasonal dynamics of the above variables, let's generate correlation charts grouped by season.</em></li></ol><p> </p><ul><li>The heatmap is a nice clean way to visualise the relatively noisy soil moisture timeseries, although for some reason I want to flip the colours round so that red means high and blue means low. I know this is against the "red = hot and dry, blue = wet" intuition so maybe ignore me!</li></ul><ol><li>I would prefer keeping the current colour map. Note, it was used in a recent publication of COSMOS-Europe, https://doi.org/10.5194/essd-14-1125-2022</li></ol><p> </p><ul><li>It might be worth adding a sentence or two about why the TDT probes don't match the CRNS VWC, or even each other, exactly. The complexity of the porous structure of soil even under "simple" grassland means that moisture can be non-uniformly distributed horizontally and vertically: two probes a few metres apart measure "extremely local" moisture (and can sometimes be trapped in a water pocket leading to artificially high VWC or be pressed against a rock and produce artificially low VWC). The COSMOS CRNS averages over all of this heterogeneity but introduces its own sources of noise (biomass water, surface water, variable depth and horizontal footprint).</li></ul><ol><li>Added and rephrased to <em>Soils contain a complex porous structure which means moisture can be non-uniformly distributed horizontally and vertically. For site measurements such as TDTS even distanced a few metres apart they measure "extremely local" moisture (and can sometimes be trapped in a water pocket leading to artificially high VWC or be pressed against a rock and produce artificially low VWC). In contrast, local measurements such as CRNS average over all of this heterogeneity but introduces its own sources of noise (biomass water, surface water, variable depth and horizontal footprint).</em></li></ol><p> </p><p>Overall, very nice overview! 8)</p>

**Comment by acocac** [comment]
<p>@<a href="https://github.com/mattfry-ceh" target="_blank">mattfry-ceh</a>, thanks for the suggestions, I've addressed all them in the new version. Please find my comments below:</p><p> </p><p>Comments from me:</p><p>In general this is great, a nice way to show the data and the tools. I like the use of the csv metadata files to use for graph labelling, etc. (which is what we meant them to be used for).</p><ol><li>The visuals won't be possible without a great dataset such as the COSMOS-UK. For instance, the metadata is very informative as it is demonstrated through the notebook.</li></ol><p> </p><p>Some specific small points:</p><ul><li>could the link at top ("the&nbsp;<a href="https://catalogue.ceh.ac.uk/documents/b5c190e4-e35d-40ea-8fbe-598da03a1185" target="_blank">2013-2019 public COSMOS-UK dataset</a>") point to the DOI as this is immutable:&nbsp;<a href="https://doi.org/10.5285/b5c190e4-e35d-40ea-8fbe-598da03a1185" target="_blank">https://doi.org/10.5285/b5c190e4-e35d-40ea-8fbe-598da03a1185</a></li></ul><ol><li>Fixed</li></ol><p> </p><ul><li>The sentence "Additional to inform near-surface soil moisture, the network collects a large number of hydrometeorological and soil data variables, including VWC measured by point-scale soil moisture sensors" doesn't quite capture it. The COSMOS sensors aren't near-surface, compared to most soil moisture sensors. One key points is that, in contrast to point sensors they measure SM over a wider footprint. How about "In addition to measuring field-scale soil moisture, the network collects a large number of hydrometeorological and soil data variables, including VWC measured by point-scale soil moisture sensors."</li></ul><ol><li>Changed</li></ol><p> </p><ul><li>Could the dataset authors text use the full citation for the dataset: "Stanley, S.; Antoniou, V.; Askquith-Ellis, A.; Ball, L.A.; Bennett, E.S.; Blake, J.R.; Boorman, D.B.; Brooks, M.; Clarke, M.; Cooper, H.M.; Cowan, N.; Cumming, A.; Evans, J.G.; Farrand, P.; Fry, M.; Hitt, O.E.; Lord, W.D.; Morrison, R.; Nash, G.V.; Rylett, D.; Scarlett, P.M.; Swain, O.D.; Szczykulska, M.; Thornton, J.L.; Trill, E.J.; Warwick, A.C.; Winterbourn, B. (2021). Daily and sub-daily hydrometeorological and soil data (2013-2019) [COSMOS-UK]. NERC Environmental Information Data Centre.&nbsp;<a href="https://doi.org/10.5285/b5c190e4-e35d-40ea-8fbe-598da03a1185" target="_blank">https://doi.org/10.5285/b5c190e4-e35d-40ea-8fbe-598da03a1185</a>"</li></ul><ol><li>Changed</li></ol><p> </p><ul><li>Could dataset authors section be called "Dataset reference and documentation", because the supporting documentation at this link is probably the most accessible to most users</li></ul><ol><li>Changed</li></ol><p> </p><ul><li>Could the "Dataset documentation" section be called "Further references" as these are more about proving background to the COSMOS network and methods.</li></ul><ol><li>Changed</li></ol><p> </p><ul><li>Under the "Note" section, which is great, thanks, can we put the link again, just to be sure! Maybe the text "available for download" could have the DOI link above.</li></ul><ol><li>Added</li></ol><p> </p><ul><li>Additional Information: again, change the dataset link to use the DOI.</li></ul><ol><li>Changed</li></ol><p> </p>

**Comment by acocac** [comment]
@mattfry-ceh @dorankhamis Thanks for all your comments. I think I agree with all them. Your domain expertise is so valuable to avoid misleading content in the notebook. Please feel free to have a look at my comments and new version in the Netlify preview [here](https://deploy-preview-50--the-environmental-ds-book.netlify.app/agriculture/sensors/agriculture-sensors-cosmosuk).

**Comment by dorankhamis** [comment]
I'm happy with the document! Though one more thing from your changes:
You've added
"CNRSs (local) and TDT (site)", where I would have actually considered the TDT as the local measurements and the CNRS as the site measurement, as the CNRS averages over the site while the TDT measures locally about a single point.

But other than that, good to go!

**Pull request merged**
