### PR TITLE
IceNet demonstrator

### PR DESCRIPTION
**Pull request by acocac**
A PR for contributing a IceNet Sea Ice Forecasting demonstrator to the Environmental AI book. The notebook:

* Clone and access the IceNet codebase to produce seasonal Artic sea ice forecast using 3 out of 25 five pre-trained IceNet models.
* Forecast a single year, 2020, from Apr 2016 to Dec 2020 ERA5 observations.
* Assess IceNet’s ice edge predictions for September forecasts at 4- to 1-month lead times.
* Compare IceNet predictions against ECMWF SEAS5 physics-based sea ice probability forecast and linear trend statistical benchmark.

Notes:
The notebook maintains the project structure of the IceNet paper repository. The mask data are generated by `gen_masks.py ` script. The remaining sample data and configuration file are downloaded from a public [zenodo](https://doi.org/10.5281/zenodo.5516869) repository.  
I have added Tensorflow 2.2.0 to the environment.yml file.

### CODE REVIEW

**Comment by acocac** [comment]
<p>I am not sure if they can be removed. Why do you suggest to remove it?</p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by acocac** [comment]
<p>Make the step simple by removing <em>network_exist</em> and <em>network_non_exist</em>&nbsp;vars</p><p> </p><pre class="ql-syntax" spellcheck="false">url = 'https://ramadda.data.bas.ac.uk/repository/entry/get/'

target_networks = [36, 42, 53]

if not os.path.exists(config['network_h5_files_folder']):
    os.makedirs(config['network_h5_files_folder'])

for target in target_networks:
    urllib.request.urlretrieve(url + f'network_tempscaled_{target}.h5?entryid=synth%3A71820e7d-c628-4e32-969f-464b7efb187c%3AL25ldXJhbF9uZXR3b3JrX21vZGVsL25ldHdvcmtfdGVtcHNjYWxlZF8zNi5oNQ%3D%3D', f'./networks/network_tempscaled_{target}.h5')
</pre>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by acocac** [comment]
<p>done, thanks!</p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by acocac** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by acocac** [comment]
<p>change to </p><h3>Download data loader configuration file</h3>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by acocac** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by acocac** [comment]
<p>which raw tuple? </p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by acocac** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by acocac** [comment]
<p>removed</p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by acocac** [comment]
<p>The word 'excels' is not correct in&nbsp;<em>IceNet excels the range of accurate sea ice forecasts</em>. You could use 'advances' (as we do in the paper abstract) or a synonym!</p><p>	Done. IceNet<em> advances...</em></p><p> </p><p>It should be&nbsp;'<em>to produce seasonal Ar</em><strong><em>c</em></strong><em>tic sea ice forecast</em><strong><em>s'</em></strong></p><p>	Done.</p><p> </p><p>It is unclear why you use ERA5 data going back to April 2016 if only forecasting 2020 &amp; Perhaps mention in 'Highlights' that you download sample data from a Zenodo repository?</p><p>	Done. * Forecast a single year, 2020, from Apr 2019 to Dec 2020 analysis-ready data 		dowloaded from a Zenodo repository.</p><p> </p><p>Can you frame this as a 'demonstrator of the IceNet forecasting system' or similar</p><p>	Done. The purpose was reframed to: <em>Demonstrate IceNet, a deep learning-based sea ice   forecasting system trained using climate simulations and observational data.</em></p><p> </p><p>Tell people that at the end of the notebook there will be some interactive visualisations, so people should 'make sure to get to the end!' or something :-)</p><p>	The last two items of the highlights: </p><p>		* Visualise IceNet’s seasonal ice edge predictions at 4- to 1-month lead times. </p><p>		* Interactive plots comparing IceNet predictions against ECMWF SEAS5 physics-based 	sea ice probability forecast and linear trend statistical benchmark.</p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by acocac** [comment]
<p>removed to make the cell shorter...</p><p> </p><pre class="ql-syntax" spellcheck="false">url = 'https://ramadda.data.bas.ac.uk/repository/entry/get/'

target_networks = [36, 42, 53]

for network in target_networks:
    urllib.request.urlretrieve(url + f'network_tempscaled_{network}.h5?entryid=synth%3A71820e7d-c628-4e32-969f-464b7efb187c%3AL25ldXJhbF9uZXR3b3JrX21vZGVsL25ldHdvcmtfdGVtcHNjYWxlZF8zNi5oNQ%3D%3D', f'./networks/network_tempscaled_{network}.h5')
</pre><p> </p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by acocac** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by acocac** [comment]
<ol><li>The description was extended to explain the benefits of using <code>xarray</code>. <em>Now we are setting up an empty </em><code><em>xarray DataArray </em></code><em>object that we will use to store IceNet's forecasts. </em><code><em>DataArrays</em></code><em> let you conveniently handle, query and visualise spatio-temporal data as the forecast predictions generated by the IceNet system.</em></li><li>Changed <code>heldout</code>&nbsp;with&nbsp;<code>forecast.</code></li></ol>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by acocac** [comment]
<p>done!</p><p> </p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by acocac** [comment]
<p>it doesn't seem to be longer necessary as we're doing a small computation.</p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by acocac** [comment]
<p><strong>Added: </strong></p><p>To analyse the forecast performance, IceNet's researchers compute two metrics, <code>Binary accuracy</code> and <code>Sea Ice Extent (SIE) error</code>. The former is generated over an active grid cell region for a given calendar month and can be seen as a normalised version of the integrated ice edge error (IIEE) (see further information of the meaning in Methods in the IceNet's [*Nature communications*](https://www.nature.com/articles/s41467-021-25257-4) paper. The latter, SIE error, is the difference between the overpredicted area and the underpredicted area. Both metrics are complementary, being the binary accuracy more robust for assessing IceNet’s relative seasonal forecast skill for September.</p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by acocac** [comment]
<p>the new notebook contains a simpler notation for the model, IceNet</p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by acocac** [comment]
<p>Not longer necessary as the computations are in the memory.</p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by acocac** [comment]
<p>Added:</p><p>It is worth to mention other pre-computed results from the Nature Communications paper can be downloaded including output results table, uncertainty, netCDF forecast of the 25 ensemble members, among others.&nbsp;</p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by acocac** [comment]
<p>the cell is considerably shorter in the new version.</p><p> </p><pre class="ql-syntax" spellcheck="false">now = pd.Timestamp.now()
new_results_df_fname = now.strftime('%Y_%m_%d_%H%M%S_forecast_results.csv')
new_results_df_fpath = os.path.join(config['forecast_results_folder'], new_results_df_fname)

print('New results will be saved to {}\n\n'.format(new_results_df_fpath))

results_df_fnames = sorted([f for f in os.listdir(config['forecast_results_folder']) if re.compile('.*.csv').match(f)])
if len(results_df_fnames) &gt;= 1:
&nbsp;&nbsp;old_results_df_fname = results_df_fnames[-1]
&nbsp;&nbsp;old_results_df_fpath = os.path.join(config['forecast_results_folder'], old_results_df_fname)
&nbsp;&nbsp;print('\n\nLoading previous results dataset from {}'.format(old_results_df_fpath))

# Load previous results, do not interpret 'NA' as NaN
results_df = pd.read_csv(old_results_df_fpath, keep_default_na=False, comment='#')

# Remove existing IceNet results
results_df = results_df[~results_df['Model'].str.startswith('IceNet')]

# Drop spurious index column if present
results_df = results_df.drop('Unnamed: 0', axis=1, errors='ignore')
results_df['Forecast date'] = [pd.Timestamp(date) for date in results_df['Forecast date']]

results_df = results_df.set_index(['Model', 'Ensemble member', 'Leadtime', 'Forecast date'])

# Add new models to the dataframe
multi_index = create_results_dataset_index([model], leadtimes, all_target_dates, model, icenet_seeds)
results_df = results_df.append(pd.DataFrame(index=multi_index)).sort_index()
</pre>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by acocac** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by acocac** [comment]
<p><code>compute_dict</code>  lines were removed.</p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by acocac** [comment]
<p>removed</p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by acocac** [comment]
<p>removed</p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by acocac** [comment]
<p><strong>Added:</strong></p><p>As we are showing in the next section, the monthly masks, stacked into a <code>DataArrays</code> object, are relevant to compute metrics only in the active grid cell region.</p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by acocac** [comment]
<p>removed</p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by acocac** [comment]
<p>Removed. Now only the head is printed in the <strong>Analysis</strong> section. </p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by acocac** [comment]
<p>removed the lines loading the file. The new version using the object in memory. </p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by acocac** [comment]
<p>ReviewNB doesn't render <code>hvPlot</code> objects. </p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by acocac** [comment]
<p>You're right, there are 12 forecast months. The cells also makes clear we are comparing IceNet, SEAS5 and linear trend benchmark.</p><p> </p><p><em>The figure below shows the mean binary accuracy versus lead time over the 12 forecasted dates for IceNet, SEAS5 and linear trend benchmark. We observe IceNet outperform SEAS5 and linear trend models at lead times of 2 months and beyond.</em></p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by acocac** [comment]
<p>ReviewNB doesn't render&nbsp;<code>hvPlot</code>&nbsp;objects.</p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by acocac** [comment]
@tom-andersson, I went through most of the suggestions and applied them to the latest version. The major changes are:

- A considerable reduction in the number of lines, from ~1000 to 700 lines. 
- Include information of the funding in the header as suggested by @scotthosking. 
- Further interaction with input/output files e.g. data loader `JSON` file and results `data.frame`
- Remove unnecessary lines e.g. compute_dict, reload files, etc.   
- Replace `heldout` by `forecast` e.g `heldout_start` > `forecast_start`
- Cross-referencing some sections of the paper and source code.

The interactive plots are not available in `ReviewNB`. If you find useful, I attach a compressed file with the rendered version of the figures in HTML [figs_html.zip](https://github.com/acocac/environmental-ai-book/files/7366607/figs_htmls.zip). This is a provisional solution while I find a better technology to display interactive plots for reviewing. 

Finally, I've been unsuccessful to change the projected coordinate system of the hover to `lat`, `lon` following this [issue#251](https://github.com/holoviz/geoviews/issues/251) in holoviz. Maybe you know a better workaround?

**Comment by acocac** [comment]
@tom-andersson I've found another technology, [notebooksharing.space](https://notebooksharing.space), which seems a feasible one for visualising interactive plots. Have a look at the notebook [here](https://notebooksharing.space/view/fb473166d5512461835fa8aedfbf195ac95a974f265dc1e4a337bcc01d9976b1#displayOptions=). @scotthosking also try it, I just discover `notebooksharing.space` after a recent tweet by [Ryan Abernathey](https://twitter.com/rabernat/status/1446495829397839875?s=20). 

While the `notebooksharing.space` looks great, I would prefer reviewers keep making comments on ReviewNB as I've found it more robust to track comments within NB versions.

**Comment by tom-andersson** [comment]
Thanks for all this @acocac! notebooksharing.space is a nice option to view the plots, although unfortunately the slides do not work. I'll stick to using the .zip files you sent.

I'm taking a look at ReviewNB now.

**Comment by tom-andersson** [comment]
<ul><li>The word 'Polar:' in the title reads strangely to me - I understand it is in the Polar section of the Environmental AI book, but perhaps this could be removed if it is clear from the book subsections?</li><li>'<em>Forecast a single year, 2020, from Apr 2019 to Dec 2020</em>' confused me initially, perhaps: '<em>Forecast a single year, 2020, using IceNet's preprocessed environmental input data downloaded from a Zenodo repository.</em>' </li><li>'ECMWF SEAS5 physics-based sea ice probability' should be 'ECMWF SEAS5 physics-based sea ice <em>concentration </em>and <em>a</em> linear trend statistical benchmark'</li></ul>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by acocac** [comment]
<ul><li>Thanks for the point about the section name in the title. The new version includes sort of tags (badges) indicating the primary (environment) and secondary (modelling, sensor) sections. I'll work in other levels of tags available in <code>sphinx-panels</code> in future version.</li><li>Changed.</li><li>Changed.</li></ul>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by acocac** [comment]
<p>- font size increased.</p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by acocac** [comment]
@tom-andersson, thanks for the great feedback. It has been very interesting to me to reproduce the IceNet paper. I've worked on most of the latest suggestion including:
- Use `sphinx-panels` [tags](https://sphinx-panels.readthedocs.io/en/latest/) to indicate the environmental setting and notebook category. The tags feature is a nice one to be implemented in the existing and future notebooks of the EnvAI book.
- List of contributors (notebook and IceNet modelling).
- `matplotlib contour` to generate the Fig 1 instead of the `hvplot contour`. 
- Fig 1 and Fig 3 work now using `panel`. The developers suggested to [embedding](https://panel.holoviz.org/user_guide/Deploy_and_Export.html#embedding) the dashboard. This is a great feature and take-away for future demonstrators.

I'll close the issue once I confirm the IceNet notebook of the `master` branch works in the Pangeo Binder.

Thanks!!  :snowflake:

**Comment by acocac** [comment]
The reviewer has recommended publication. Some future work is needed to improve text.

**Comment by acocac** [comment]
Nick @nbarlowATI suggested some changes for the IceNet demo (see [PR#6](https://github.com/alan-turing-institute/PangeoExamples/pull/6) in the Turing Pangeo Examples repository). I incorporated them and added Nick as reviewer.

**Pull request merged**
