### PR TITLE
[WIP] Notebook - general-exploration-landcover_io

### LINKED ISSUE #7: [NBI] Exploring Land Cover Data
## What is the notebook about?
This notebook introduces raster land cover data with simple manipulation and basic exploratory analysis techniques. The notebook will be based largely on the existing [notebooks I have used for teaching](https://github.com/jamesdamillington/UK-LCM) and will examine:
- Overview of raster data characteristics
- Reading raster data
- Plotting categorical raster maps
- Analysing aggregate change (through bars charts and similar visualisation) 
- Analysing zonal change (using ancillary vector data)
- Analysing pixel-by-pixel change (including use of sankey diagrams)

There are now many data sources of classified (categorical) land cover data that are useful for Environmental Data Science. These include:
- [ESA CCI land cover](https://www.esa-landcover-cci.org/), 300m spatial resolution global extent for years 1992-2015 
- [Copernicus Global Land Cover](https://zenodo.org/communities/copernicus-land-cover), 100m spatial resolution global extent for years 2015-2019 
- [USGS LCMAP](https://www.usgs.gov/special-topics/lcmap/data), 30m spatial resolution for USA for years 1985-2020
- [UKCEH LCMs](https://www.ceh.ac.uk/data/ukceh-land-cover-maps), various spatial resolutions for UK for various years 1990-2020
- [mapbiomas](https://mapbiomas.org/en), 30m spatial resolution for Brazil for years 1985-2020

Considerations for deciding which of these sources to use in this notebook include:
- _licencing:_ some of these data sources are have open licences, others are more restrictive (notably UKCEH LCMs)
- _data access:_ some data sources can easily be accessed programmatically via API, others less easily
- _data volume:_ fine-grained data over large extents result in large data (e.g. ESA CCI 300m global extent for a single year is ~300MB)

Code and packages used in this notebook will initially be those used in the original teaching notebooks, notably:
- [rasterio](https://pypi.org/project/rasterio/) with [numpy `ndarray`s](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html)
- pandas and geopandas
- matplotlib and [seaborn](https://seaborn.pydata.org/)

In time, the code can be changed to use packages from the [pangeo ecosystem](https://pangeo.io/packages.html)

## Data Science Component

- [ ] Sensor visualisation
- [ ] Preprocessing
- [ ] Modelling
- [ ] Post-processing
- [x] Other: Data Manipulation and Basic Analysis (best fits in the [Exploration section](https://the-environmental-ds-book.netlify.app/gallery/exploration.html) of the current Gallery)

## Checklist:

- [x] Input data, pipeline and/or model are public with license/citation
- [x] The proposed notebook reuses existing codebase
- [x] The proposed notebook uses open-source packages
- [ ] The proposed notebook is associated to existing publication(s)

### PR DESCRIPTION
**Pull request by acocac**
## Before review
- [ ] Work in progress
- [x] Ready for review
- [ ] Need help!

## Description

Add the executable notebook _Exploring Land Cover Data (Impact Observatory)_ (see the notebook idea in issue alan-turing-institute/eds-ideas-transfer#7).

## Motivation and Context

New notebook contribution to the **exploration** theme.

## How has this been tested?

GitHub actions deployed the forked template by the main author, @jamesdamillington, then the repo was transferred to the EnvDS book organisation (see https://github.com/Environmental-DS-Book/general-exploration-landcover_io).

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] New notebook and/or content
- [ ] Documentation notebook/content update 
- [ ] Other (please describe):
- [ ] Feature change (upgrade version)

## Checklist:

- [x] My code follows the code style of this project: [Python](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [CONTRIBUTING](../CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests to cover my changes
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage)

### CODE REVIEW

**Comment by acocac** [comment]
@jamesdamillington the proof of the notebook is ready for your revision. 

Please feel free it the Netlify preview box above or click [here](https://deploy-preview-110--the-environmental-ds-book.netlify.app/gallery/exploration/general-exploration-landcover_io/general-exploration-landcover_io). 

To reduce the length of the notebook, all cells with static/interactive plots and others with considerable code have the **Click to show** button. Note this only hides cells in the html version and not when you open the file in Binder or locally.

Please confirm and provide comments where necessary:
- [ ] Does the proof match the original and revised content of the notebook?
- [ ] Are Binder and RoHub badges within the preview working?
- [ ] Are the proposed **Click to show** buttons ok for you? If not, which ones do you suggest removing?

(optional) @annefou @aedebus can you confirm if you have any comments of the proof?

**Comment by jamesdamillington** [comment]
@acocac  Thanks for all your work pulling the proof together! It all looks good to me _except for one thing_: in [Section 3](https://deploy-preview-110--the-environmental-ds-book.netlify.app/gallery/exploration/general-exploration-landcover_io/general-exploration-landcover_io#analysing-aggregate-change) the _Tip_ box says
> We could also do an interactive plot with hvplot for Pandas data (not shown here to reduce notebook filesize - uncomment to run yourself).

But the code was _not_ commented and so the interactive plot _does_ show in the notebook... 

We should either remove the _Tip_ box (preferable I think) or comment the code out and re-compile so the `hvplot` doesn't appear. 

Everything else looks okay (Binder takes a long time to boot but once it has, everything seems to work okay)

**Comment by acocac** [comment]
@jamesdamillington thanks for the quick reply! 
I'm keeping the tip box, and just rephrasing the tip to:
_We could also do an interactive plot with `hvplot` for Pandas data (see the cell below)._
Let me fix it now!

**Comment by acocac** [comment]
@jamesdamillington can you double check the preview? it should have the suggested change in the tip box. 

May I ask if you can complete the checkbox of my previous comment. This is a sort of final confirmation that the notebook is ok to go (:

**Comment by jamesdamillington** [comment]
Hi @acocac  Thanks for the edit. Everything looks great and good to go, but how do I check the boxes?

**Comment by acocac** [comment]
> Hi @acocac Thanks for the edit. Everything looks great and good to go, but how do I check the boxes?

Cool - Thanks for confirming all looks good to you! Regarding the checking boxes, you can copy them into a new comment and check them in case you cannont click-on each of them at my comment.

**Comment by jamesdamillington** [comment]
- [x] Does the proof match the original and revised content of the notebook?
- [x] Are Binder and RoHub badges within the preview working?
- [x] Are the proposed Click to show buttons ok for you?

@acocac

**Comment by acocac** [comment]
Excellent.

> * [x]  Does the proof match the original and revised content of the notebook?
> * [x]  Are Binder and RoHub badges within the preview working?
> * [x]  Are the proposed Click to show buttons ok for you?
> 
> @acocac

Cool - thanks for confirming all is ok. 

Apart from the nice and well-documented sections of the notebook, I've learnt how to properly cross-reference them which would be a very useful tip to recommend in the WIP PR#115 on improved guidelines. 

I hope the publication process has been a positive experience for you and reviewers!

**Pull request merged**
