### PR TITLE
Update gallery

### LINKED ISSUE #134: [ENH] New Gallery
## Feature Request

The current gallery chapter contains all notebooks indexed by theme with a drop-down list. This isn't the most attractive and accessible format for readers/users. 

## Describe the solution you'd like

@scotthosking has suggested a great idea to replace the drop-down list with a single section pointing to a gridded gallery similar to [Pangeo Gallery](https://gallery.pangeo.io/) or [Scivision](https://sci.vision/#/model-grid).

## Describe alternatives you've considered

- Manually adding grids using [Sphinx-design](https://sphinx-design.readthedocs.io/en/latest/grids.html) 
- Automatically add items to the gallery with a YML. See [JupyterBook Gallery](https://github.com/executablebooks/meta/blob/1292f4296e81780f2bc8dd8ee8cf7384640ba418/docs/conf.py#L102)

### PR DESCRIPTION
**Pull request by acocac**
## Before review
- [ ] Work in progress
- [x] Ready for review
- [ ] Need help!

## Description

Move all notebooks into a single folder and add a gridded version of the Gallery.

## Motivation and Context

The current gallery chapter contains all notebooks indexed by theme with a drop-down list. This isn't the most attractive and accessible format for readers/users.

## How has this been tested?

Local. MacOS.

### Steps to set up machine readable notebook repositories
- [ ] Check Quay.io image and robot permissions
- [ ] Replace workflow files
- [ ] Modify config.json
- [ ] Rename notebook name
- [ ] Change license file
- [ ] Change conda env name 
- [ ] Change org name
- [ ] Change notebook name .ipynb
- [ ] Change repo name
- [ ] Change folder structure name (notebook)
- [ ] Change badges and opticon

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] New notebook and/or content
- [ ] Documentation notebook/content update 
- [ ] Other (please describe):
- [x] Feature change (upgrade version)

## Checklist:

- [x] My code follows the code style of this project: [Python](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [CONTRIBUTING](../CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests to cover my changes
- [ ] I have tested the changes and verified that they work and don't break anything (as well as I can manage)

### CODE REVIEW

**Comment by scotthosking** [comment]
This is really looking great - I suggest we drop the "List" dropdown menu and the list of notebooks in the sidebar. I feel the gallary is so much more engaging and informative, and duplicating information may lead to confusion

**Comment by scotthosking** [comment]
My other comment relates to the landing page. I suggest steer users more directly towards the gallary, e.g., by showing 3-4 highlight gallary cards with a link to the full set (similar to https://sci.vision), or even merge the front page and gallary into one page. 

The gallary is really clear and my sense is that a user would instantly undertand what the EDSbook is all about - by comparison the current front page is a little text heavy and isn't as eye catching

**Comment by scotthosking** [comment]
Also, what does the "regular" tag mean within each Gallary card?

**Comment by acocac** [comment]
> This is really looking great - I suggest we drop the "List" dropdown menu and the list of notebooks in the sidebar. I feel the gallary is so much more engaging and informative, and duplicating information may lead to confusion

@scotthosking thanks for having a look at the proposed gallery chapter! The dropdown menu feature isn't possible to remove. The current version of Jupyter book requires I declare the local path to each of the notebooks that will be rendered in HTML (see for instance [here](https://github.com/alan-turing-institute/environmental-ds-book/blob/d7305a3c3c48184cf24c5f9db069cb8bfeae1f6e/book/_toc.yml#L22)). My inmediate solution is to have a single "Gallery" section below the NOTEBOOK chapter. If you click-on Gallery, it goes to the gridded version, however it'll also show all notebooks in a list. I reckon this might be confusing, but I hope to find a better workaround in future major releases.

**Comment by acocac** [comment]
> My other comment relates to the landing page. I suggest steer users more directly towards the gallary, e.g., by showing 3-4 highlight gallary cards with a link to the full set (similar to https://sci.vision), or even merge the front page and gallary into one page.
> 
> The gallary is really clear and my sense is that a user would instantly undertand what the EDSbook is all about - by comparison the current front page is a little text heavy and isn't as eye catching

The idea is great. I'll implement it in a separate PR and give credits accordignly!

**Comment by acocac** [comment]
> Also, what does the "regular" tag mean within each Gallary card?

This is a new tag and aims to distinguish Regular submissions to other categories e.g hackathon, special issues, etc.

**Comment by acocac** [comment]
@annefou I'd appreciate a feedback and some checks of the proposed gallery. A large task was renaming all notebook repositories using the w3id generated in RoHub. This is a safer option than a manual ID. Please double check if the links of each notebook thumbnail work. I'll remove the step of defining a notebook name in the author guidelines. Finally, note the Gallery dropdown list will be removed in future releases as I've suggested to @scotthosking.

**Review by annefou — APPROVED** [review]
I really like the gallery and agree with all the previous comments e.g. remove gallery dropdown list, etc. I checked the llnks each notebook thumbnail and they all work very well. Really awesome work @acocac Thank you!!!

**Pull request merged**
