### PR TITLE
added detectree example notebook

### PR DESCRIPTION
**Pull request by shmh40**
To do:
-  Read in model weights with intake (is this possible @acocac ?
- Provide graphical interface with leafmap so users can see predictions and tiff geographically
- Small tidy possible - extend summary, move comments to markdown

### CODE REVIEW

**Comment by shmh40** [comment]
- Updated notebook with interactive leafmap
- This currently works for **shapefiles**, but I cannot make it work for **tiffs**, even using the example from the documentation

**Comment by shmh40** [comment]
Added code so forest-modelling-detectree-v2 will run on cpu

**Comment by acocac** [comment]
@shmh40  Thanks for such great contribution. I left some suggestions. Be free to explore them in [ReviewNB](https://app.reviewnb.com/acocac/environmental-ai-book/pull/4/discussion/). Some key adjusments are:
- Create a folder structure to facilitate load and export demostrator files. Under this proposed structure, users can easily replace the folder routes with the preferred ones in a local machine or docker image.
- Remove some commented lines. Keep only those that are strictly necessary.
- Propose using `hvplot` instead of `leafmap` for the interactive plotting.

**Comment by shmh40** [comment]
<p>Added hyperlink</p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by shmh40** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by shmh40** [comment]
<p>Agreed</p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by shmh40** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by shmh40** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by shmh40** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by shmh40** [comment]
<p>Done - thank you</p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by shmh40** [comment]
<p>Thanks for all the comments Alejandro! Very helpful. </p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by shmh40** [comment]
<p>Currently testing this</p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by shmh40** [comment]
<p>Very helpful, thanks</p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by shmh40** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by shmh40** [comment]
<p>Agreed, done</p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by shmh40** [comment]
<p>Done - sensible, thank you...</p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by shmh40** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by shmh40** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by shmh40** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by shmh40** [comment]
<p>Nice</p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by shmh40** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by shmh40** [comment]
<p>Done</p><p> </p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by shmh40** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by shmh40** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by shmh40** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by shmh40** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by shmh40** [comment]
v4 of the notebook now uploaded with desired changes and some minor amendments to mapping - added code to save the interactive map.

**Comment by acocac** [comment]
<p>It seems there are some version problems with recent pytorch and detectron2 installed via !python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'. I would suggest to add an extra line above ## install detectron2:</p><p> </p><pre class="ql-syntax" spellcheck="false"># install pytorch
!pip -q install torch==1.8.0 
!pip -q install torchvision==0.9.0
</pre><p> </p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by acocac** [comment]
<p>(:</p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by acocac** [comment]
@shmh40 thanks for implementing the suggestions. I just made a minor comments. 
FYI, You don't need to create a new notebook file for each version. Please make the minor changes on `forest-modelling-detectree-v4.ipynb `. Let me know if you succeed to explore further the hover of `hvplot`. Otherwise, the notebook is ready to publish!

**Comment by shmh40** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by shmh40** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by shmh40** [comment]
Made final changes, and added function to see confidence score in hvplot. Good to go!

**Comment by shmh40** [comment]
<p>Done!</p>

---

 <a href='https://app.reviewnb.com/acocac/environmental-ai-book/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by shmh40** [comment]
<p>All changes complete! </p>

**Comment by acocac** [comment]
Thanks @shmh40, it was great to have your contribution for the forest domain. I hope you learnt some useful python packages for handling geospatial datasets. I made some minor style adjustments to the notebook and now it's good to go (:

**Pull request merged**
